### ISSUE TITLE
Question/Meta: What is the theoretically/mathematically best scaler to use with this?

### ISSUE THREAD

**Issue by Carl-Robert** [Artoriuz/glsl-pixel-clipper#2]
Hi!

In your imagemagick comparison you stated that this antiring filter was designed to be used with: `--scale=ewa_robidoux --scale-param1=0 --scale-param2=0.5` . However in your updated mpv scalers comparison the passages referencing this scaler as well as `catmull_rom` for downscaling are removed.

Is this filter now recommended to be used with `lanczos` instead for both up- and downscaling?

Please don't respond with "try and see which looks the best", since I'm curious about the theoretical/mathematical choice here :)

**Comment by Artoriuz** [comment]
It was removed from the page because the point was evaluating AR itself and not the various combinations individually.

As for whether it's recommended to be used with Lanczos, the answer is no. Catrom + AR is still a better solution than Lanczos + AR for downsampling. You can use the shader with any filter, it wasn't "designed" with Lanczos in mind.

AR becomes more important as the filter becomes sharper, but AR itself can be used with anything to remove the overshoots and (hopefully) increase image quality. It works particularly well with polar Catrom (the filter you mentioned) because polar Catrom is exceptionally sharp, but it works even better with a 2-lobes Sinc for example.

My advice is, treat is as an alternative to the built-in AR functionality. It's sometimes better and sometimes worse, but generally speaking the solutions are close enough and the difference is imperceptible.
